# -*- coding: utf-8 -*-
"""project1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omlGxSsA-7cq5xlPJOScpSXCVk2hH4YU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.linear_model import LinearRegression

data = pd.read_csv('tips.csv')
data.head()

day_count = data['day'].value_counts()
fig =  plt.pie(day_count,labels=data['day'].unique(),autopct='%1.1f%%',startangle=90)
plt.show()

plt.scatter(data['total_bill'],data['tip'], color='cyan')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.title('Total Bill vs Tip')
plt.show()

data['smoker']=data['smoker'].replace({'Yes':1,'No':0})
data['sex']=data['sex'].replace({'Female':1,'Male':0})
data['day']=data['day'].replace({'Thur':1,'Fri':2,'Sat':3,'Sun':4})
data['time']=data['time'].replace({'Lunch':1,'Dinner':0})
print(data)

correlate_matrix = data.corr()
sns.heatmap(correlate_matrix, annot=True)
plt.show()

x=data.drop('tip',axis=1)
y=data['tip']
print(x)
print(y)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print(f"Model Accuracy: {accuracy:.2%}")

sample_input = np.array([[20, 1, 0, 3, 1, 2]])
predicted_tip = model.predict(sample_input)
print(f"Predicted Tip: ${predicted_tip[0]:.2f}")